apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pyms2-wasm
  name: pyms2-wasm
  namespace: ytsai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyms2-wasm
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/userVolume: '[{"name":"a10-auth-public-filter","configMap":{"name":"a10-auth-public-filter"}}]'
        sidecar.istio.io/userVolumeMount: '[{"mountPath":"/var/local/wasm","name":"a10-auth-public-filter"}]'
      labels:
        app: pyms2-wasm
        istio-envoy-filter: a10-auth-public-filter
    spec:
      containers:
      - env:
        - name: KAFKA_HOST
          value: cp-helm-charts-cp-kafka.kafka.svc.cluster.local:9092
        - name: KAFKA_REGISTRY_HOST
          value: http://cp-helm-charts-cp-schema-registry.kafka.svc.cluster.local:8081
        - name: OPENSEARCH_HOST
          value: elasticsearch-master.logging.svc.cluster.local
        - name: OPENSEARCH_PORT
          value: "9200"
        - name: OPENSEARCH_USERNAME
          value: admin
        - name: OPENSEARCH_PASSWORD
          value: admin
        - name: DATA_SERVICE_SESSION_URL
          value: http://sys-data-session.saas-framework.svc.cluster.local:30020
        - name: DATA_SERVICE_TENANT_URL
          value: http://sys-data-tenant.saas-framework.svc.cluster.local:30010
        - name: DATA_SERVICE_PRODUCT_URL
          value: http://sys-data-product.saas-framework.svc.cluster.local:30011
        image: us-phoenix-1.ocir.io/axqel8fpeyhe/sidp-ref-microservice-python:pyms2
        imagePullPolicy: Always
        name: pyms2-wasm
        ports:
        - containerPort: 30034
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: oracle-docker-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: pyms2-wasm
  namespace: ytsai
spec:
  ports:
  - name: http
    port: 30034
    protocol: TCP
    targetPort: 30034
  selector:
    app: pyms2-wasm
