pyms:
  services:
    requests:
      data: ""
    swagger:
        path: "swagger"
        file: "swagger.yaml"
        url: "/ui/"
        project_dir: "project.views"
    

  config:
    DEBUG: false
    TESTING: false
    APP_NAME: pyms2
    APPLICATION_ROOT : /pyms2
    SQLALCHEMY_TRACK_MODIFICATIONS: true
    SECRET_KEY: "gjr39dkjn344_!67#"
    DATABASE: db.sqlite3
    SQLALCHEMY_DATABASE_URI: sqlite:///db.sqlite3
